#Java 6 Specifics
- name: Check for Oracle Java {{ java_version }} archive
  stat: 
    path: "{{ media_dir }}/jdk-{{ java_version }}-linux-{{ java_arch }}.bin"
  register: stoarch6

- name: Download Oracle Java {{ java_version }}
  tags: java
  s3_file:
    bucket: "{{ java_s3_bucket }}"
    object: "{{ java_s3_base }}jdk-{{ java_version }}-linux-{{ java_arch }}.bin"
    dest: "{{ media_dir }}/jdk-{{ java_version }}-linux-{{ java_arch }}.bin"
    mode: get
    aws_access_key: "{{ s3_key|default(omit) }}"
    aws_secret_key: "{{ s3_secret|default(omit) }}"
  when: not stoarch6.stat.exists and http_use != true

- name: Download Oracle Java {{ java_version }} from HTTP
  tags: java
  get_url:
    url: "{{ http_base_url }}/jdk-{{ java_version }}-linux-{{ java_arch }}.bin"
    dest: "{{ media_dir }}/jdk-{{ java_version }}-linux-{{ java_arch }}.bin"
  when: http_use == true

- name: Extract Oracle Java {{ java_version }}
  tags: java
  command: /bin/bash {{ media_dir }}/jdk-{{ java_version }}-linux-{{ java_arch }}.bin -noregister
  args:
    chdir: "{{ java_install_path }}"
    creates: "{{ jdk_home }}"
